[package]
name = "backup"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
regex = "1.10.5"
sha256 = "1.5.0"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.10.1"
